/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainFrame.java
 *
 * Created on 1 Sep, 2012, 11:59:15 PM
 */

package fHide;
import java.applet.Applet;
import java.awt.*;
import javax.swing.JApplet;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.net.URI;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.BevelBorder;
import javax.swing.border.EtchedBorder;
/*
<applet code="app" width=1000 height=700>

</applet>
*/
/**
 *
 * @author AJAY-PREM
 */
public class mainFrame extends javax.swing.JFrame {
    int arrIndex=0;
    public int x=600,y=300;
    ArrayList<String> sar=new ArrayList<String>();
    BufferedReader br;
        Image img;

    /** Creates new form mainFrame */
    public mainFrame() {
        initComponents();

        PassPro.setTitle("Enter Password to Proceed");
        PassPro.setLocation(580,300);
        PassPro.setSize(185,110);
        passField.setFont(new Font("Arial",Font.ITALIC,18));
        passField.setEchoChar('^');
        PassPro.setVisible(true);
        PassPro.setAlwaysOnTop(true);

        setIconImage(Toolkit.getDefaultToolkit().getImage(mainFrame.class.getResource("iconApp.png")));
       unHidePop.setIconImage(Toolkit.getDefaultToolkit().getImage(mainFrame.class.getResource("iconApp.png")));
       optionPop.setIconImage(Toolkit.getDefaultToolkit().getImage(mainFrame.class.getResource("iconApp.png")));
       setIconImage(Toolkit.getDefaultToolkit().getImage(mainFrame.class.getResource("iconApp.png")));
       
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPop = new javax.swing.JDialog();
        hideRadio = new javax.swing.JRadioButton();
        strongRadio = new javax.swing.JRadioButton();
        okButton = new javax.swing.JButton();
        closeOpt = new javax.swing.JButton();
        unHidePop = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        unHidePopTextArea = new javax.swing.JTextArea();
        unHidePopText = new javax.swing.JTextField();
        unHidePopButton = new javax.swing.JButton();
        UnHidePopPrev = new javax.swing.JButton();
        unHidePopNext = new javax.swing.JButton();
        closeUnHidePop = new javax.swing.JButton();
        Open = new javax.swing.JButton();
        aboutUsPop = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        aboutUsText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        knowUs = new javax.swing.JTextPane();
        exitButton1 = new javax.swing.JButton();
        authorPop = new javax.swing.JPopupMenu();
        welcome = new javax.swing.JPopupMenu();
        PassPro = new javax.swing.JDialog();
        passField = new javax.swing.JPasswordField();
        OkPro = new javax.swing.JButton();
        CancelPro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PassPro1 = new javax.swing.JDialog();
        passField1 = new javax.swing.JPasswordField();
        OkPro1 = new javax.swing.JButton();
        CancelPro1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        hideLink = new javax.swing.JTextField();
        unHideLink = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        Tools = new javax.swing.JMenu();
        hideMoreFiles = new javax.swing.JMenuItem();
        unHideFiles = new javax.swing.JMenuItem();
        changePass = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutUs = new javax.swing.JMenuItem();

        optionPop.setResizable(false);
        optionPop.setUndecorated(true);

        hideRadio.setFont(new java.awt.Font("Courier New", 0, 14));
        hideRadio.setText("Hide");
        hideRadio.setToolTipText("Hides Files as Windows provided");

        strongRadio.setFont(new java.awt.Font("Courier New", 0, 14));
        strongRadio.setText("Strong Hide");
        strongRadio.setToolTipText("Strongly Hides Files and cannot be recovered witout fHide");

        okButton.setFont(new java.awt.Font("Courier New", 0, 14));
        okButton.setText("Im Sure !!");
        okButton.setToolTipText("Click For OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        closeOpt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fHide/a.png"))); // NOI18N
        closeOpt.setToolTipText("Exit");
        closeOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeOptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionPopLayout = new javax.swing.GroupLayout(optionPop.getContentPane());
        optionPop.getContentPane().setLayout(optionPopLayout);
        optionPopLayout.setHorizontalGroup(
            optionPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPopLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(optionPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionPopLayout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(optionPopLayout.createSequentialGroup()
                        .addComponent(hideRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(strongRadio)))
                .addGap(19, 19, 19))
        );
        optionPopLayout.setVerticalGroup(
            optionPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPopLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(optionPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hideRadio)
                    .addComponent(strongRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closeOpt, 0, 0, Short.MAX_VALUE)
                    .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        unHidePop.setResizable(false);
        unHidePop.setUndecorated(true);

        unHidePopTextArea.setColumns(20);
        unHidePopTextArea.setEditable(false);
        unHidePopTextArea.setFont(new java.awt.Font("Courier New", 0, 16));
        unHidePopTextArea.setRows(5);
        jScrollPane1.setViewportView(unHidePopTextArea);

        unHidePopText.setEditable(false);
        unHidePopText.setFont(new java.awt.Font("Courier New", 0, 16));
        unHidePopText.setForeground(new java.awt.Color(0, 0, 204));

        unHidePopButton.setText("UnHide");
        unHidePopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unHidePopButtonActionPerformed(evt);
            }
        });

        UnHidePopPrev.setText("prev");
        UnHidePopPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnHidePopPrevActionPerformed(evt);
            }
        });

        unHidePopNext.setText("next");
        unHidePopNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unHidePopNextActionPerformed(evt);
            }
        });

        closeUnHidePop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fHide/a.png"))); // NOI18N
        closeUnHidePop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeUnHidePopActionPerformed(evt);
            }
        });

        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout unHidePopLayout = new javax.swing.GroupLayout(unHidePop.getContentPane());
        unHidePop.getContentPane().setLayout(unHidePopLayout);
        unHidePopLayout.setHorizontalGroup(
            unHidePopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unHidePopLayout.createSequentialGroup()
                .addGroup(unHidePopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, unHidePopLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(UnHidePopPrev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(unHidePopNext)
                        .addGap(10, 10, 10)
                        .addComponent(Open)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(unHidePopButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeUnHidePop, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(unHidePopLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(unHidePopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(unHidePopLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(unHidePopText, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))))
                .addContainerGap())
        );
        unHidePopLayout.setVerticalGroup(
            unHidePopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unHidePopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unHidePopText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(unHidePopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(unHidePopLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(unHidePopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unHidePopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UnHidePopPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Open, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unHidePopNext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(unHidePopLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(closeUnHidePop, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );

        aboutUsPop.setResizable(false);
        aboutUsPop.setUndecorated(true);

        aboutUsText.setColumns(20);
        aboutUsText.setEditable(false);
        aboutUsText.setFont(new java.awt.Font("Courier New", 0, 16));
        aboutUsText.setRows(5);
        aboutUsText.setText(" fHide is the is windows-based \n Application,which enables you\n to hide your files/folders...\n It provides strong Hide Option..\n\n And Security of your data is our \n prime duty and we love to do \nthat....\n\t\t    This is \n        © forward s/ash inc.\n\t\t    product.\n\t     (version 1.0.0)");
        aboutUsText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutUsTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutUsTextMouseExited(evt);
            }
        });
        jScrollPane2.setViewportView(aboutUsText);

        knowUs.setEditable(false);
        knowUs.setFont(new java.awt.Font("Lucida Handwriting", 1, 24));
        knowUs.setForeground(java.awt.Color.red);
        knowUs.setText("Know Us.");
        knowUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                knowUsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                knowUsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                knowUsMouseExited(evt);
            }
        });
        jScrollPane3.setViewportView(knowUs);

        exitButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fHide/a.png"))); // NOI18N
        exitButton1.setToolTipText("Exit");
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aboutUsPopLayout = new javax.swing.GroupLayout(aboutUsPop.getContentPane());
        aboutUsPop.getContentPane().setLayout(aboutUsPopLayout);
        aboutUsPopLayout.setHorizontalGroup(
            aboutUsPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsPopLayout.createSequentialGroup()
                .addGroup(aboutUsPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(aboutUsPopLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aboutUsPopLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        aboutUsPopLayout.setVerticalGroup(
            aboutUsPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsPopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutUsPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );

        PassPro.setTitle("Enter password:");
        PassPro.setAlwaysOnTop(true);
        PassPro.setResizable(false);
        PassPro.setUndecorated(true);

        passField.setBackground(new java.awt.Color(255, 255, 0));
        passField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        OkPro.setFont(new java.awt.Font("Rod", 0, 11));
        OkPro.setText("LOG-IN");
        OkPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkProActionPerformed(evt);
            }
        });

        CancelPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fHide/a.png"))); // NOI18N
        CancelPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelProActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setText("Enter Password:");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout PassProLayout = new javax.swing.GroupLayout(PassPro.getContentPane());
        PassPro.getContentPane().setLayout(PassProLayout);
        PassProLayout.setHorizontalGroup(
            PassProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassProLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PassProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addGroup(PassProLayout.createSequentialGroup()
                        .addComponent(OkPro, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CancelPro))
                    .addGroup(PassProLayout.createSequentialGroup()
                        .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PassProLayout.setVerticalGroup(
            PassProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassProLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PassProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(OkPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CancelPro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PassPro.getAccessibleContext().setAccessibleParent(menuBar);

        PassPro1.setTitle("Enter password:");
        PassPro1.setAlwaysOnTop(true);
        PassPro1.setResizable(false);
        PassPro1.setUndecorated(true);

        passField1.setBackground(new java.awt.Color(255, 255, 0));
        passField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        OkPro1.setFont(new java.awt.Font("Rod", 0, 11));
        OkPro1.setText("OK");
        OkPro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkPro1ActionPerformed(evt);
            }
        });

        CancelPro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fHide/a.png"))); // NOI18N
        CancelPro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelPro1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setText("Enter Password:");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout PassPro1Layout = new javax.swing.GroupLayout(PassPro1.getContentPane());
        PassPro1.getContentPane().setLayout(PassPro1Layout);
        PassPro1Layout.setHorizontalGroup(
            PassPro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassPro1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PassPro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addGroup(PassPro1Layout.createSequentialGroup()
                        .addComponent(OkPro1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CancelPro1))
                    .addGroup(PassPro1Layout.createSequentialGroup()
                        .addComponent(passField1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PassPro1Layout.setVerticalGroup(
            PassPro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassPro1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PassPro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(OkPro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CancelPro1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("fHide");
        setBackground(new java.awt.Color(204, 204, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        hideLink.setEditable(false);
        hideLink.setBackground(Color.WHITE);
        hideLink.setFont(new java.awt.Font("Courier New", 0, 14));
        hideLink.setText("Hide More Files/Folders");
        hideLink.setToolTipText("Hide Files");
        hideLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hideLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hideLinkMouseExited(evt);
            }
        });

        unHideLink.setBackground(Color.WHITE);
        unHideLink.setEditable(false);
        unHideLink.setFont(new java.awt.Font("Courier New", 0, 14));
        unHideLink.setText("Un-Hide Files/Folders");
        unHideLink.setToolTipText("Show Files");
        unHideLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unHideLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unHideLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unHideLinkMouseExited(evt);
            }
        });
        unHideLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unHideLinkActionPerformed(evt);
            }
        });

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fHide/a.png"))); // NOI18N
        exitButton.setToolTipText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        File.setText("File");

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fHide/a.png"))); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        File.add(exit);

        menuBar.add(File);

        Tools.setText("Options");

        hideMoreFiles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fHide/hide.png"))); // NOI18N
        hideMoreFiles.setText("Hide");
        hideMoreFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideMoreFilesActionPerformed(evt);
            }
        });
        Tools.add(hideMoreFiles);

        unHideFiles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fHide/unhide.png"))); // NOI18N
        unHideFiles.setText("Un-Hide");
        unHideFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unHideFilesActionPerformed(evt);
            }
        });
        Tools.add(unHideFiles);

        changePass.setText("Change Password");
        changePass.setEnabled(false);
        changePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassActionPerformed(evt);
            }
        });
        Tools.add(changePass);

        menuBar.add(Tools);

        helpMenu.setText("Help");

        aboutUs.setText("Know Us");
        aboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsActionPerformed(evt);
            }
        });
        helpMenu.add(aboutUs);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hideLink, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(unHideLink, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hideLink, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(unHideLink, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        JFileChooser jcf;
        private File [] files;
        fileWrite fw;
        FileReader fr;
        fileRead fr1;
    private void hideMoreFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideMoreFilesActionPerformed
        jcf=new JFileChooser("D:\\");
        jcf.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        jcf.setMultiSelectionEnabled(true);
        jcf.setLocation(x,y);
        jcf.setDragEnabled(true);
        jcf.setSize(200,200);
        int act=jcf.showDialog(menuBar,"Hide Files");
        files=jcf.getSelectedFiles();

        if(files!=null){ 
        if(act==JFileChooser.APPROVE_OPTION){
        optionPop.setLocation(x,y);
        optionPop.setSize(261,129);
        optionPop.setTitle("Provide Hide Type");
        optionPop.setVisible(true);
        }
        }
    }//GEN-LAST:event_hideMoreFilesActionPerformed
    String cmd=new String("");
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        
        optionPop.setVisible(false);
        fw=new fileWrite();
        fr1=new fileRead();
        String f=fr1.reader();
        for(int i=0;i<files.length;i++){
        if(!f.contains(""+files[i]))
        fw.writer(new StringBuilder(""
           +files[i]));
        }
        if(hideRadio.isSelected()){
        cmd="Attrib +H";
        }
        else if(strongRadio.isSelected()){
        cmd="Attrib +H +S";
        }
        for(int i=0;i<files.length;i++){
        try{
        Runtime.getRuntime().exec(cmd+" "+files[i]);
        }
        catch(IOException e){
        
        }
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void hideLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideLinkMouseEntered
        hideLink.setBackground(Color.CYAN);
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_hideLinkMouseEntered

    private void hideLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideLinkMouseExited
        hideLink.setBackground(Color.WHITE);
        setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_hideLinkMouseExited
    ActionEvent aevt;
    private void hideLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideLinkMouseClicked
        hideMoreFilesActionPerformed(aevt);
    }//GEN-LAST:event_hideLinkMouseClicked

    private void unHideLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unHideLinkMouseEntered
        unHideLink.setBackground(Color.CYAN);
                setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_unHideLinkMouseEntered

    private void unHideLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unHideLinkMouseExited
        unHideLink.setBackground(Color.WHITE);
                setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_unHideLinkMouseExited

    private void unHideLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unHideLinkMouseClicked
        unHideFilesActionPerformed(aevt);
    }//GEN-LAST:event_unHideLinkMouseClicked
        JTextField atf[];
        JCheckBox[] acb;


    private void unHideFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unHideFilesActionPerformed
        try{

        fr=new FileReader(new File(fileWrite.fd));
        br=new BufferedReader(fr);
        String s,full=new String("");
        int i=0;
        while((s=br.readLine())!=null){
        i++;
        if(s.length()>0)
        {
        full=full+s+System.getProperty("line.separator");
        sar.add(s);
        }
        }
        br.close();
        if(sar.size()>0){
        unHidePopTextArea.setText(full);
        unHidePopTextArea.setText(full);
        unHidePopText.setText(sar.get(arrIndex));
        unHidePop.setSize(500,330);
        unHidePopText.setBackground(Color.ORANGE);
        unHidePop.setTitle("UnHide Hidden Files ");
        int a=(unHidePopTextArea.getText().indexOf(sar.get(arrIndex)));
        int b=(unHidePopTextArea.getText().indexOf(sar.get(arrIndex))+sar.get(arrIndex).length());
        unHidePopTextArea.select(a,b);
        if(sar.size()==1){
        UnHidePopPrev.setEnabled(false);
        unHidePopNext.setEnabled(false);
        
        }
        unHidePop.setLocation(x-100,y-50);
        unHidePop.setVisible(true);
        }
        else{
        JOptionPane.showMessageDialog(null,"No Files Hidden by fHide","Null",JOptionPane.INFORMATION_MESSAGE);
        }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"No Files Hidden by fHide","Null",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_unHideFilesActionPerformed

    private void unHidePopNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unHidePopNextActionPerformed
        arrIndex++;
        if(arrIndex>=sar.size()){
        arrIndex=0;
        }
        int a=(unHidePopTextArea.getText().indexOf(sar.get(arrIndex)));
        int b=(unHidePopTextArea.getText().indexOf(sar.get(arrIndex))+sar.get(arrIndex).length());
        unHidePopTextArea.select(a,b);
        unHidePopText.setText(sar.get(arrIndex));
        
    }//GEN-LAST:event_unHidePopNextActionPerformed

    private void UnHidePopPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnHidePopPrevActionPerformed
        arrIndex--;
        if(arrIndex==-1){
        arrIndex=sar.size()-1;
        }
        unHidePopText.setText(sar.get(arrIndex));
        int a=(unHidePopTextArea.getText().indexOf(sar.get(arrIndex)));
        int b=(unHidePopTextArea.getText().indexOf(sar.get(arrIndex))+sar.get(arrIndex).length());
        unHidePopTextArea.select(a,b);
    }//GEN-LAST:event_UnHidePopPrevActionPerformed

    String rem;
        File mFile=new File(fileWrite.fd);
    private void unHidePopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unHidePopButtonActionPerformed
        String s,full=new String("");
        try{
        Runtime.getRuntime().exec("Attrib -H -S "+unHidePopText.getText());
        String xx=unHidePopTextArea.getText();
        if(xx.contains(unHidePopText.getText())){
        fr=new FileReader(mFile);
        br=new BufferedReader(fr);
        while((s=br.readLine())!=null){
        if(!s.equalsIgnoreCase(unHidePopText.getText())&&s.length()>2)
        full=full+s+System.getProperty("line.separator");
        }
        br.close();
        mFile.delete();
        fw=new fileWrite();
        fw.writer(new StringBuilder(full));
        }
        unHidePopTextArea.setText(full);
        rem=unHidePopText.getText();
        sar.remove(sar.indexOf(unHidePopText.getText()));
        if(sar.size()!=0)
        unHidePopText.setText(sar.get(0));
        else{
        unHidePopText.setText("No more Files Hidden by fHide");
        }
        arrIndex=0;
        }
        catch(IOException e){}
        if(sar.size()<=0)
        {
        unHidePopButton.setEnabled(false);
        UnHidePopPrev.setEnabled(false);
        unHidePopNext.setEnabled(false);
        }
                try{
            Runtime.getRuntime().exec("explorer "+rem);
        }
        catch(Exception e){}
        if(unHidePopText.getText().equals("No more Files Hidden by fHide"))
        {
        Open.setEnabled(false);
        }

    }//GEN-LAST:event_unHidePopButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void closeUnHidePopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeUnHidePopActionPerformed
        unHidePop.setVisible(false);
    }//GEN-LAST:event_closeUnHidePopActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        exitButtonActionPerformed(evt);
    }//GEN-LAST:event_exitActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        if(evt.getKeyChar()=='e'){
        setEnabled(false);
        }
    }//GEN-LAST:event_formKeyReleased

    private void knowUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_knowUsMouseClicked
        if(Desktop.isDesktopSupported()) {
            try{
                Desktop.getDesktop().browse(new URI("https://www.facebook.com/ForwardSlash.FW"));
            } catch(Exception e) {
            }
        }
}//GEN-LAST:event_knowUsMouseClicked

    private void knowUsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_knowUsMouseEntered
        knowUs.setCursor(new Cursor(Cursor.HAND_CURSOR));
        knowUs.setBackground(Color.LIGHT_GRAY);
}//GEN-LAST:event_knowUsMouseEntered

    private void knowUsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_knowUsMouseExited
        knowUs.setBackground(Color.WHITE);
}//GEN-LAST:event_knowUsMouseExited

    private void aboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsActionPerformed
        aboutUsPop.setSize(410,350);
        aboutUsPop.setLocation(x-100,y-50);
        jScrollPane3.setVerticalScrollBarPolicy(jScrollPane3.VERTICAL_SCROLLBAR_NEVER);
        aboutUsPop.setTitle("forward Write inc.");
        aboutUsPop.setVisible(true);

    }//GEN-LAST:event_aboutUsActionPerformed

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton1ActionPerformed
        aboutUsPop.setVisible(false);
    }//GEN-LAST:event_exitButton1ActionPerformed

    private void closeOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeOptActionPerformed
        optionPop.setVisible(false);
}//GEN-LAST:event_closeOptActionPerformed

    private void unHideLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unHideLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unHideLinkActionPerformed
JTextArea jta=new JTextArea("Credits To Mr. Ajay Prem Shankar..(Dated: 2.09.2012)");

    private void aboutUsTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsTextMouseExited
        authorPop.setVisible(false);
    }//GEN-LAST:event_aboutUsTextMouseExited

    private void aboutUsTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsTextMouseEntered
        authorPop.add(jta);
        authorPop.setLocation(x-31,y+250);
        authorPop.setVisible(true);
        
    }//GEN-LAST:event_aboutUsTextMouseEntered

    private void OkProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkProActionPerformed
        PassPro.setVisible(false);
        String pass=new String(passField.getPassword());
        info inf=new info();
        File f=new File("C:\\Users\\Public\\Documents\\obj.ser");
        try{
        fis=new FileInputStream(f);
        ois=new ObjectInputStream(fis);
        inf=(info)ois.readObject();
        ois.close();
        }
        catch(Exception e){}
        if(!pass.equals("qwerty1")){
            JOptionPane.showMessageDialog(null,"You Entered Wrong Password");
        System.exit(0);}

                setSize(240,140);
                setLocation(x,y);
    /*            try{
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                }
                catch(Exception e){
                System.out.println("LOOK failed");
                }
*/
                setTitle("fHide");
                setEnabled(true);
                setVisible(true);

    }//GEN-LAST:event_OkProActionPerformed

    private void CancelProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelProActionPerformed
        PassPro.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_CancelProActionPerformed

    private void changePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassActionPerformed
    jLabel2.setText("Enter Old Password");
    PassPro1.setVisible(true);
    PassPro1.setLocation(580,300);
    PassPro1.setSize(185,110);
    passField1.setFont(new Font("Arial",Font.ITALIC,18));
    passField1.setEchoChar('^');

    }//GEN-LAST:event_changePassActionPerformed
String passw="qwerty1";
FileOutputStream fos;
FileInputStream fis;
ObjectOutputStream oos;
ObjectInputStream ois;
    private void OkPro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkPro1ActionPerformed
    PassPro1.setVisible(false);
            info inf=new info();

    if(jLabel2.getText().contains("Old")){
          File f=new File("C:\\Users\\Public\\Documents\\obj.ser");
          try{
          fis=new FileInputStream(f);
          ois=new ObjectInputStream(fis);
          inf=(info)ois.readObject();
          ois.close();
          }
          catch(Exception e){}
  if(new String(passField1.getPassword()).equals(inf.password)){
    jLabel2.setText("Enter new Password");
    PassPro1.setVisible(true);
    PassPro1.setLocation(580,300);
    PassPro1.setSize(185,110);
    passField1.setFont(new Font("Arial",Font.ITALIC,18));
    passField1.setEchoChar('^');
    }
    }
    else{
        String psw=new String(passField1.getPassword());
        inf.password=psw;
        File f=new File("C:\\Users\\Public\\Documents\\obj.ser");
        try{
    if(f.exists()){
    f.delete();
    }
    fos=new FileOutputStream("C:\\Users\\Public\\Documents\\obj.ser");
    oos=new ObjectOutputStream(fos);
    oos.writeObject(inf);
    oos.close();
    }
        catch(Exception e){}
    }
    }//GEN-LAST:event_OkPro1ActionPerformed

    private void CancelPro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelPro1ActionPerformed
        PassPro1.setVisible(false);
    }//GEN-LAST:event_CancelPro1ActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed

        try{
            Runtime.getRuntime().exec("explorer "+unHidePopText.getText());
        }
        catch(Exception e){}
    }//GEN-LAST:event_OpenActionPerformed

  public class info implements Serializable{
  String password;
  }


    /**
    * @param args the command line arguments
    */
info in=new info();

  public static void main(String args[]){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                try{
                mainFrame mF=new mainFrame();

                }
                catch(Exception e){}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelPro;
    private javax.swing.JButton CancelPro1;
    private javax.swing.JMenu File;
    private javax.swing.JButton OkPro;
    private javax.swing.JButton OkPro1;
    private javax.swing.JButton Open;
    private javax.swing.JDialog PassPro;
    private javax.swing.JDialog PassPro1;
    private javax.swing.JMenu Tools;
    private javax.swing.JButton UnHidePopPrev;
    private javax.swing.JMenuItem aboutUs;
    protected javax.swing.JDialog aboutUsPop;
    private javax.swing.JTextArea aboutUsText;
    private javax.swing.JPopupMenu authorPop;
    private javax.swing.JMenuItem changePass;
    private javax.swing.JButton closeOpt;
    private javax.swing.JButton closeUnHidePop;
    private javax.swing.JMenuItem exit;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitButton1;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JTextField hideLink;
    private javax.swing.JMenuItem hideMoreFiles;
    private javax.swing.JRadioButton hideRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane knowUs;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton okButton;
    private javax.swing.JDialog optionPop;
    private javax.swing.JPasswordField passField;
    private javax.swing.JPasswordField passField1;
    private javax.swing.JRadioButton strongRadio;
    private javax.swing.JMenuItem unHideFiles;
    private javax.swing.JTextField unHideLink;
    private javax.swing.JDialog unHidePop;
    private javax.swing.JButton unHidePopButton;
    private javax.swing.JButton unHidePopNext;
    private javax.swing.JTextField unHidePopText;
    private javax.swing.JTextArea unHidePopTextArea;
    private javax.swing.JPopupMenu welcome;
    // End of variables declaration//GEN-END:variables

}
